version: 2.1
jobs:
  compile:
   docker:
    - image: inok2341/anu:latest
      auth:
   resource_class: large
   steps:
      - run:
          command: |
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
           export DEBIAN_FRONTEND=noninteractive
           apt update
           apt install sudo
           apt install time
           apt install rclone
           #git clone https://github.com/akhilnarang/scripts bscripts && cd bscripts && bash setup/android_build_env.sh && cd ..
           mkdir -p ~/.config/rclone
           printf "[remote]\ntype = drive\nscope = drive\ntoken = {"access_token":"ya29.a0ARrdaM-31yElVZUy3zSe-8HO6FRDSqLnZIX9FPPb0rvogJ2tdWHDN1tcahG_jKCW_mmFEdmMtp1cZFwd-hmXeINfXBL65o7zdWhzlegKudHzQled6Reui6ikzd3E0KNEXyvEBBZY7mF4uUFMZkTGHngMDe3L","token_type":"Bearer","refresh_token":"1//0gA-CKsbHffjLCgYIARAAGBASNwF-L9IrQC8B1I7eJI0D96zFIgJpHW75juaf5D1fTOjR_5DFcT2X89bpJyurhQwZqBfUojOb5aA","expiry":"2021-10-23T22:46:21.231221878+05:30"}\nclient_id = 9495530072-2kceoeg3tb8tjt8n2k20vqgatsd6gt7d.apps.googleusercontent.com\nclient_secret = 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" > ~/.config/rclone/rclone.conf
           DEBIAN_FRONTEND=noninteractive
           sudo apt install python3 -y
           sudo ln -sf /usr/bin/python3 /usr/bin/python
           git config --global user.name "phoenix-1708"
           git config --global user.email "harikumar1708@gmail.com"
           git config --global color.ui true
           mkdir -p /tmp/ccache
           rclone copy remote:ccache/ci2/ccache.tar.gz /tmp -P
           cd /tmp
           sudo time tar xf ccache.tar.gz
           cd /tmp
           echo "============================"
           echo "Syncing The Sources..."
           echo "============================"
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
           cd /tmp/rom
           repo init -q --no-repo-verify --depth=1 -u https://github.com/Evolution-X/manifest -b snow -g default,-mips,-darwin,-notdefault
           git clone https://github.com/phoenix-1708/local_manifest.git --depth=1 -b evox12 .repo/local_manifests
           repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"
           echo "============================"
           echo "Sync Completed!"
           echo "============================"
           echo "============================"
           #Building
           echo "Starting the Build..."
           echo "============================"
           cd /tmp/rom
           export CCACHE_DIR=/tmp/ccache
           export CCACHE_EXEC=$(which ccache)
           export USE_CCACHE=1
           ccache -M 20G
           ccache -o compression=true
           ccache -z
           source build/envsetup.sh > /dev/null 2>&1
           lunch evolution_sweet-userdebug > /dev/null 2>&1
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="$(echo "${var_cache_report_config}")"
           export ALLOW MISSING DEPENDENCIES=true
           export SKIP_ABI_CHECKS=true
           export SKIP_API_CHECKS=true
           mka evolution -j$(nproc --all)
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip) Completed!"
           echo "Uploading the Build...."
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip)"
           rclone copy /tmp/rom/out/target/product/laurel_sprout/*.zip remote:sweet -P
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip) Uploaded Successfully!"
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Download link https://withered-lab-e844.harikumar1708.workers.dev/sweet/$(cd /tmp/rom/out/target/product/sweet/ && ls *.zip)"
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
           git clone https://github.com/phoenix-1708/anu.git && cd anu
           bash ziping.sh
           cd /tmp
           curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
           rclone copy ccache.tar.gz remote:ccache/ci2 -P
           echo "Build Uploaded Successfully!"
           
           
           
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
